A complete documentation for o2
HardeepAsrani/o2 pull request #7
Opened 2018-03-04 04:13 UTC by KumarAbhirup

Here it is! I have created documentations for the o2 Library.

2018-03-07 00:39 UTC, HardeepAsrani requested changes
@KumarAbhirup  I did a small review so can you please change it? Also, delete the package-lock.json file.

2018-03-07 00:39 UTC, HardeepAsrani commented on README.md
> +o2 is a WordPress Customizer library for adding custom controls to the Customizer such as:
O2 should be in capital letters.

2018-03-07 00:39 UTC, HardeepAsrani commented on README.md
> +o2 lacks complete documentation. If you like the library and want to contribute, help with documentation will be appreciated.
O2 here again.

2018-03-07 00:39 UTC, HardeepAsrani commented on controls/color-palette/README.md
> +# Using the Color Palette
Make control title names #Color Palette Control for WordPress Customizer and similar

2018-03-07 00:39 UTC, HardeepAsrani commented on controls/color-palette/README.md
> +- Hope you have downloaded and installed o2 on your theme. If you have installed that, then you may proceed for further steps.
In such sections, you can just link to main readme.md files

2018-03-07 00:39 UTC, HardeepAsrani commented on controls/color-palette/README.md
> +For more info, you may consider this [5 minute read](http://www.hardeepasrani.com/2017/10/color-palette-control-for-wordpress-customizer/).
No need to mention my site here.

2018-03-07 00:39 UTC, HardeepAsrani commented on controls/color-palette/README.md
> +For more info, you may consider this [5 minute read](http://www.hardeepasrani.com/2017/10/color-palette-control-for-wordpress-customizer/).
Do the same in all other readme.md files

2018-03-07 09:51 UTC, KumarAbhirup commented
Yeah, made all your suggested changes. Be sure you notify if something left 👍

2018-03-08 22:55 UTC, HardeepAsrani approved these changes
Thanks!

2018-03-08 22:56 UTC, merged